/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as FanclubRouteImport } from './routes/fanclub'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'
import { Route as FeedIndexRouteImport } from './routes/feed.index'
import { Route as FeedPostIdRouteImport } from './routes/feed.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const FanclubRoute = FanclubRouteImport.update({
  id: '/fanclub',
  path: '/fanclub',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/$artistId',
  path: '/$artistId',
  getParentRoute: () => ArtistsRoute,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedRoute,
} as any)
const FeedPostIdRoute = FeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => FeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/chart': typeof ChartRoute
  '/fanclub': typeof FanclubRoute
  '/feed': typeof FeedRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/service': typeof ServiceRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/warehouse': typeof WarehouseRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/feed/': typeof FeedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/fanclub': typeof FanclubRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/service': typeof ServiceRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/warehouse': typeof WarehouseRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/artists': typeof ArtistsIndexRoute
  '/feed': typeof FeedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/chart': typeof ChartRoute
  '/fanclub': typeof FanclubRoute
  '/feed': typeof FeedRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/service': typeof ServiceRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/warehouse': typeof WarehouseRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/feed/': typeof FeedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/chart'
    | '/fanclub'
    | '/feed'
    | '/login'
    | '/me'
    | '/service'
    | '/signup'
    | '/store'
    | '/support'
    | '/warehouse'
    | '/artists/$artistId'
    | '/feed/$postId'
    | '/artists/'
    | '/feed/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart'
    | '/fanclub'
    | '/login'
    | '/me'
    | '/service'
    | '/signup'
    | '/store'
    | '/support'
    | '/warehouse'
    | '/artists/$artistId'
    | '/feed/$postId'
    | '/artists'
    | '/feed'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/chart'
    | '/fanclub'
    | '/feed'
    | '/login'
    | '/me'
    | '/service'
    | '/signup'
    | '/store'
    | '/support'
    | '/warehouse'
    | '/artists/$artistId'
    | '/feed/$postId'
    | '/artists/'
    | '/feed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  ChartRoute: typeof ChartRoute
  FanclubRoute: typeof FanclubRoute
  FeedRoute: typeof FeedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  ServiceRoute: typeof ServiceRoute
  SignupRoute: typeof SignupRoute
  StoreRoute: typeof StoreRoute
  SupportRoute: typeof SupportRoute
  WarehouseRoute: typeof WarehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fanclub': {
      id: '/fanclub'
      path: '/fanclub'
      fullPath: '/fanclub'
      preLoaderRoute: typeof FanclubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/feed/': {
      id: '/feed/'
      path: '/'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof FeedRoute
    }
    '/feed/$postId': {
      id: '/feed/$postId'
      path: '/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof FeedPostIdRouteImport
      parentRoute: typeof FeedRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface FeedRouteChildren {
  FeedPostIdRoute: typeof FeedPostIdRoute
  FeedIndexRoute: typeof FeedIndexRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedPostIdRoute: FeedPostIdRoute,
  FeedIndexRoute: FeedIndexRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  ChartRoute: ChartRoute,
  FanclubRoute: FanclubRoute,
  FeedRoute: FeedRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  ServiceRoute: ServiceRoute,
  SignupRoute: SignupRoute,
  StoreRoute: StoreRoute,
  SupportRoute: SupportRoute,
  WarehouseRoute: WarehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
